**Building a Machine Learning Model to Predite a BankNotes fake or Real**

In [1]:
# IMPORT LIBRARIES

import numpy as np                    # Mathematical & Array Operations
import pandas as pd                   # Tabular Data & CSV Handling
import matplotlib.pyplot as plt       # Basic Graph Visualization
import seaborn as sns                 # Advanced Statistical Charts

from sklearn.model_selection import train_test_split   # Dataset Splitting
from sklearn.preprocessing import StandardScaler        # Feature Scaling
from sklearn.preprocessing import LabelEncoder          # Categorical Encoding

from sklearn.linear_model import LogisticRegression    # ML Algorithm
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report # Evaluation

import joblib                          # Model Persistence (Save/Load)

In [7]:
from google.colab import files
Uploaded = files.upload()

Saving BankNote_Authentication.csv to BankNote_Authentication.csv

In [8]:
df = pd.read_csv("BankNote_Authentication.csv")

In [9]:
df.head()

   variance  skewness  curtosis  entropy  class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [10]:
df.tail()

      variance  skewness  curtosis  entropy  class
1367   0.40614   1.34920   -1.4501 -0.55949      1
1368  -1.38870  -4.87730    6.4774  0.34179      1
1369  -3.75030 -13.45860   17.5932 -2.77710      1
1370  -3.56370  -8.38270   12.3930 -1.28230      1
1371  -2.54190  -0.65804    2.6842  1.19520      1

In [11]:
df.shape

(1372, 5)

In [12]:
df.dtypes

variance    float64
skewness    float64
curtosis    float64
entropy     float64
class         int64
dtype: object

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1372 entries, 0 to 1371
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   variance  1372 non-null   float64
 1   skewness  1372 non-null   float64
 2   curtosis  1372 non-null   float64
 3   entropy   1372 non-null   float64
 4   class     1372 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 53.7 KB

In [14]:
df.describe()

          variance     skewness     curtosis      entropy        class
count  1372.000000  1372.000000  1372.000000  1372.000000  1372.000000
mean      0.433735     1.922353     1.397627    -1.191657     0.444606
std       2.842763     5.869047     4.310030     2.101013     0.497103
min      -7.042100   -13.773100    -5.286100    -8.548200     0.000000
25%      -1.773000    -1.708200    -1.574975    -2.413450     0.000000
50%       0.496180     2.319650     0.616630    -0.586650     0.000000
75%       2.821475     6.814625     3.179250     0.394810     1.000000
max       6.824800    12.951600    17.927400     2.449500     1.000000

In [15]:
df.isnull()

      variance  skewness  curtosis  entropy  class
0        False     False     False    False  False
1        False     False     False    False  False
2        False     False     False    False  False
3        False     False     False    False  False
4        False     False     False    False  False
...        ...       ...       ...      ...    ...
1367     False     False     False    False  False
1368     False     False     False    False  False
1369     False     False     False    False  False
1370     False     False     False    False  False
1371     False     False     False    False  False

[1372 rows x 5 columns]

In [16]:
df.isnull().sum()

variance    0
skewness    0
curtosis    0
entropy     0
class       0
dtype: int64

In [17]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1367    False
1368    False
1369    False
1370    False
1371    False
Length: 1372, dtype: bool

In [18]:
df.duplicated().sum()

np.int64(24)

**Visualization**

In [20]:
df.columns

Index(['variance', 'skewness', 'curtosis', 'entropy', 'class'], dtype='object')

**Seperate Features**

In [22]:
# X = Target column
X = df.drop("class", axis=1)

# y = Only target column
y = df["class"]

**One-Hot Encoding**

In [23]:
# One-Hot Encoding for Unordered Categorical Features in X
X = pd.get_dummies(X, drop_first=True, dtype=int)

**Train-Test-Split**

In [24]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42  )

**Feature Scaling**

In [25]:
scaler = StandardScaler()

# Train data
X_train = scaler.fit_transform(X_train)

# Test data
X_test = scaler.transform(X_test)

**Build model**

In [53]:
# 1. LOGISTIC REGRESSION

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# Build & Train Model
logistic_model = LogisticRegression(max_iter=1000, random_state=42)
logistic_model.fit(X_train, y_train)

# Prediction
y_pred = logistic_model.predict(X_test)
y_prob = logistic_model.predict_proba(X_test)

# Evaluation
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.9781818181818182
              precision    recall  f1-score   support

           0       0.99      0.97      0.98       148
           1       0.97      0.98      0.98       127

    accuracy                           0.98       275
   macro avg       0.98      0.98      0.98       275
weighted avg       0.98      0.98      0.98       275

In [54]:
# 2 . DECISION TREE
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Build & Train (No Scaling Needed!)
dt_model = DecisionTreeClassifier(criterion='gini', max_depth=5, random_state=42)
dt_model.fit(X_train, y_train)

# Prediction
y_pred = dt_model.predict(X_test)

# Evaluation
print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred))

Decision Tree Accuracy: 0.9672727272727273

In [55]:
# 3.SVM

from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

# Build & Train (Scaling REQUIRED)
model = SVC(kernel='rbf', C=1.0, probability=True, random_state=42)
model.fit(X_train, y_train)

# Prediction
y_pred = model.predict(X_test)

# Evaluation
print("SVM Accuracy:", accuracy_score(y_test, y_pred))

SVM Accuracy: 1.0

In [56]:
# 4 . KNN
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Build & Train (Scaling REQUIRED)
model = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
model.fit(X_train, y_train)

# Prediction
y_pred = model.predict(X_test)

# Evaluation
print("KNN Accuracy:", accuracy_score(y_test, y_pred))

KNN Accuracy: 1.0

In [57]:
# N-B
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

# Build & Train
model = GaussianNB()
model.fit(X_train, y_train)

# Prediction
y_pred = model.predict(X_test)

# Evaluation
print("Naive Bayes Accuracy:", accuracy_score(y_test, y_pred))

Naive Bayes Accuracy: 0.8072727272727273

In [58]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Logistic Regression")
print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Logistic Regression
Accuracy: 0.9781818181818182
[[144   4]
 [  2 125]]
              precision    recall  f1-score   support

           0       0.99      0.97      0.98       148
           1       0.97      0.98      0.98       127

    accuracy                           0.98       275
   macro avg       0.98      0.98      0.98       275
weighted avg       0.98      0.98      0.98       275

In [59]:
from sklearn.tree import DecisionTreeClassifier

decision_tree_model = DecisionTreeClassifier(random_state=42)
decision_tree_model.fit(X_train, y_train)

y_pred = decision_tree_model.predict(X_test)

print("Decision Tree")
print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Decision Tree
Accuracy: 0.9818181818181818
[[148   0]
 [  5 122]]
              precision    recall  f1-score   support

           0       0.97      1.00      0.98       148
           1       1.00      0.96      0.98       127

    accuracy                           0.98       275
   macro avg       0.98      0.98      0.98       275
weighted avg       0.98      0.98      0.98       275

In [60]:
from sklearn.svm import SVC

svm_model = SVC()
svm_model.fit(X_train, y_train)

y_pred = svm_model.predict(X_test)

print("SVM")
print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

SVM
Accuracy: 1.0
[[148   0]
 [  0 127]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       148
           1       1.00      1.00      1.00       127

    accuracy                           1.00       275
   macro avg       1.00      1.00      1.00       275
weighted avg       1.00      1.00      1.00       275

In [61]:
from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train, y_train)

y_pred = knn_model.predict(X_test)

print("KNN")
print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

KNN
Accuracy: 1.0
[[148   0]
 [  0 127]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       148
           1       1.00      1.00      1.00       127

    accuracy                           1.00       275
   macro avg       1.00      1.00      1.00       275
weighted avg       1.00      1.00      1.00       275

In [62]:
from sklearn.naive_bayes import GaussianNB

nb_model = GaussianNB()
nb_model.fit(X_train, y_train)

y_pred = nb_model.predict(X_test)

print("Naive Bayes")
print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Naive Bayes
Accuracy: 0.8072727272727273
[[133  15]
 [ 38  89]]
              precision    recall  f1-score   support

           0       0.78      0.90      0.83       148
           1       0.86      0.70      0.77       127

    accuracy                           0.81       275
   macro avg       0.82      0.80      0.80       275
weighted avg       0.81      0.81      0.80       275

In [63]:
import pandas as pd

results = []

models = {
    "Logistic Regression": LogisticRegression(),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "SVM": SVC(),
    "KNN": KNeighborsClassifier(n_neighbors=5),
    "Naive Bayes": GaussianNB()
}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    acc = accuracy_score(y_test, y_pred)

    results.append([name, acc])

comparison = pd.DataFrame(results, columns=["Algorithm", "Accuracy"])
print(comparison)

             Algorithm  Accuracy
0  Logistic Regression  0.978182
1        Decision Tree  0.981818
2                  SVM  1.000000
3                  KNN  1.000000
4          Naive Bayes  0.807273

In [64]:
import joblib

joblib.dump(logistic_model, "logistic_model.pkl")
joblib.dump(dt_model, "dt_model.pkl")
joblib.dump(svm_model, "svm_model.pkl")
joblib.dump(knn_model, "knn_model.pkl")
joblib.dump(nb_model, "nb_model.pkl")

['nb_model.pkl']

In [67]:
import joblib

models = {
    "logistic_model": joblib.load("logistic_model.pkl"),
    "dt_model": joblib.load("dt_model.pkl"),
    "svm_model": joblib.load("svm_model.pkl"),
    "knn_model": joblib.load("knn_model.pkl"),
    "nb_model": joblib.load("nb_model.pkl")
}

for name, model in models.items():
    print(name, "loaded successfully!")

logistic_model loaded successfully!
dt_model loaded successfully!
svm_model loaded successfully!
knn_model loaded successfully!
nb_model loaded successfully!